package com.nfcpass.domain.model

/**
 * Domain model representing an NFC pass.
 * This is the business logic representation used throughout the app.
 *
 * @property id Unique identifier for the pass (generated by Supabase)
 * @property userId ID of the user who owns this pass
 * @property passId The unique pass identifier that gets emulated via NFC
 * @property passName User-friendly name for the pass (e.g., "Gym Membership")
 * @property organization Organization that issued the pass (e.g., "Gold's Gym")
 * @property isActive Whether this pass is currently active for NFC emulation
 * @property expiryDate ISO 8601 date string when the pass expires (optional)
 * @property createdAt ISO 8601 timestamp when the pass was created
 * @property updatedAt ISO 8601 timestamp when the pass was last updated
 */
data class Pass(
    val id: String,
    val userId: String,
    val passId: String,
    val passName: String,
    val organization: String,
    val isActive: Boolean = false,
    val expiryDate: String? = null,
    val link: String? = null,
    val businessId: String? = null,
    val createdAt: String,
    val updatedAt: String
) {
    /**
     * Checks if the pass is currently valid (not expired)
     */
    fun isValid(): Boolean {
        if (expiryDate == null) return true
        // TODO: Implement actual date comparison
        return true
    }

    /**
     * Returns a formatted display string for the pass
     */
    fun displayName(): String = "$passName - $organization"
}
